apiVersion: v1
kind: Pod
metadata:
  name: kafka-connect-ui
  namespace: kafka
spec:
  containers:
  - name: kafka-connect-ui
    image: landoop/kafka-connect-ui
    env:
    - name: CONNECT_URL
      value: http://kafka-cp-kafka-connect:8082
    ports:
    - containerPort: 8000
      name: connect-ui
      protocol: TCP
