apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave-scope-ingress
  namespace: weave-scope
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: weave-scope.jx.35.233.117.189.nip.io
    http:
      paths:
      - backend:
          serviceName: weave-scope-weave-scope
          servicePort: 80
        path: /
