skinparam reverse

component "<img:https://s3-eu-west-1.amazonaws.com/aws-ec2-eu-1-opendatasoft-staticfileset/datasncf/logo>" as SNCF

package "Cluster Kubernetes" as k8s {
    component "<img:https://www.rust-lang.org/logos/rust-logo-32x32.png>" as rust
    queue "Kafka" as kafka
    component "Kafka Connect" as connect
    database "Elastic" as elastic
}

SNCF->rust
rust->kafka
kafka->connect
connect->elastic